### ISSUE TITLE
Are you planning to continue this project?

### ISSUE THREAD

**Issue by bishnu-subedi** [ransurf/pythonchessprogram#1]
Lately I'm working on a chess project myself and while doing a little research work on some of the libraries and programs, I stumbled upon your video on Youtube & I think you implemented a nice idea from the scratch and build this.

Although you already mentioned about some of the missing features in your project like "preventing castling while the path is under attack & in check" and "En-passant", I still think there are a little bit more to be done like the conditions of checkmate. But having said that I think most of the in-game part is done pretty neat by yourself and its already there. 

Also I would like to know what do you think of someone contributing to your project and may be work on some fix and added features?!

Oh and btw, when I did run the program it worked well but I think when there are too many clicks at random pieces it tends to alter the turn to move, not much just a glitch maybe!

**Comment by ransurf** [comment]
Hey there!

I haven't really thought about combing back and improving the program, but
you are definitely free to work on it :) I'm fairly new to GitHub, so I'm
not really sure on how to add others to a project. If you're able to
implement the missing features, I'm sure you'd help out many people who
watch the video ;)
As for the move glitch, I haven't experienced that myself (but at the same
time I don't think I did much troubleshooting lmao).
Glad to see my code could be put to some good use, it wasn't made with the
intention for collaboration so I hope you're able to still understand it
somewhat :p

John R
